variables:
  GIT_DEPTH: 10

stages:
  - PEP8
  - unit tests
  - smoke tests
  
#Conformity Checks
PEP8_Conformity:
 stage: PEP8
 image: geoazis/sentimentanalysis:latest
 allow_failure: true
 script:
   - "echo Running PEP8 Conformity checks to src folder"
   - "cd src"
   - "pytest --pep8 --disable-warnings"
 tags:
   - jarvis


# Unit tests
Unit_Tests:
 stage: unit tests
 image: geoazis/sentimentanalysis:latest
 allow_failure: true
 script:
   - "echo Running Unit Tests"
 tags:
   - jarvis 
   
# Smoke tests
Smoke_Tests:
 stage: smoke tests
 image: geoazis/sentimentanalysis:latest
 allow_failure: true
 script:
   - "echo Running smoke Tests"
 tags:
   - jarvis 
