variables:
  GIT_DEPTH: 10

stages:
  - PEP8
  - fetch
  - data
  - interface
  - threholds
  
  
  
  
#PEP8_Comformity:
#  stage: PEP8
#  image: CREATE A DOCKER IMAGE TO RUN ON SERVER
#  script:
#    - "pytest --pep8 --disable-warnings"
#  tags:
#    - jarvis
  
Fetch_data_and_models:
  stage: fetch
  script:
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "dvc remote modify --local nielspi password projectesa"
    - "dvc pull"
#    - "ls -la"
#    - "bash run_sentiment_analyzer.sh"
  tags:
    - audio

Data_validation:
  stage: data
  script:
    - "echo Testing data schema and values"
  tags:
    - audio
    
    
Interface_validation: 
  stage: interface
  script:
    - "echo Testing DNNs interface specificationTINY CHANGE"
  tags:
    - audio


Threshold_validation: 
  stage: threholds
  script: 
    - "echo Testing DNN metrics against threshold values"
  tags:
    - audio