variables:
  GIT_DEPTH: 10

stages:
  - PEP8
  - fetch
  - data
  - interface
  - threholds
  - updating
  
#Conformity Checks
PEP8_Conformity:
 stage: PEP8
 image: geoazis/sentimentanalysis:latest
 allow_failure: true
 script:
   - "echo Running PEP8 Conformity checks to src folder"
   - "ls -la"
   - "pytest --pep8 --disable-warnings src"
 tags:
   - jarvis

Fetch_data_and_models:
  stage: fetch
  image: geoazis/sentimentanalysis:latest
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script:
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "dvc remote modify --local nielspi password projectesa"
    - "dvc pull -f"
  tags:
    - audio

Data_validation:
  stage: data
  image: geoazis/sentimentanalysis:latest
  script:
    - "echo Testing data schema and values"
  tags:
    - audio
    
Interface_validation: 
  stage: interface
  image: geoazis/sentimentanalysis:latest
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script:
    - "echo Testing DNNs interface specification"
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "pytest tests/test_cases/Model_test_cases/ --disable-warnings"
  tags:
    - audio
  allow_failure: true


Threshold_validation: 
  stage: threholds
  image: geoazis/sentimentanalysis:latest
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script: 
    - "echo Testing DNN metrics against threshold values"
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "python tests/compute_models_performance.py"
    - "pytest tests/test_cases/Threshold_test_cases/ --disable-warnings"

  tags:
    - audio
    
# Copy accepted model from candidate to deployment push to dvc and git
# Update configuration values

# Updating_deployed_model:
# stage: updating
#  cache:
#    key: default
#    paths:
#        - prod_data/test/
#        - prod_models/candidate/
# script:
#   - "source /home/pi/Documents/esa/venv/bin/activate"
#   - "python tests/update_configuration_file.py"
#   - "python tests/copy_to_deployment.py"
#   - "remove from candidate folder"
#   - "dvc commit"
#   - "dvc push"
# We need to find out how gitlab runner pushes to gitlab
#   - "git add ."
#   - "git commit -m "${userstory}"
#   - "git push"
