stages:
  - triggers

Candidate_model_assessment:
  stage: triggers
  trigger:
    include: model_verification/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - prod_models.dvc
      - prod_data.dvc
      - src/raspi_candidate_config.yml

Code_verification:
  stage: triggers
  trigger:
    include: code_verification/.gitlab-ci.yml
    strategy: depend