stages:
  - triggers

trigger_a:
  stage: triggers
  trigger:
    include: Model_verification/.gitlab-ci.yml

trigger_b:
  stage: triggers
  trigger:
    include: Code_verification/.gitlab-ci.yml
  only:
    changes:
      - prod_models.dvc
      - prod_data.dvc
