model_type: "Sequential"
parameters:
  adam_lr: 0.001
  batch_size: 32
  epochs: 10
  pretrained_models_dir: "./prod_models/candidate" 
  retrained_models_dir: "./prod_models/candidate"
  pretrained_model_name: "seq_3conv_modules_5emotions"
  retrained_model_name: "seq_3conv_modules_5emotions_ret"
  feature_train_data_directory: "./data/features/Sequential_5emotions/train"
  feature_test_data_directory: "./data/features/Sequential_5emotions/test"
  feature_validation_data_directory: "./data/features/Sequential_5emotions/validation"