model_type: "sequential"
parameters:
  adam_lr: 0.001
  batch_size: 32
  epochs: 10
  pretrained_models_dir: "../prod_models/candidate" 
  pretrained_model_name: "seq_3conv_modules_be_nice"
  retrained_models_dir: "../prod_models/candidate"
  retrained_model_name: "seq_3conv_modules_be_nice_ret_v1"
  train_data_directory: "../data/features/sequential"
  validation_data_directory: "../data/features/sequential"
  test_data_directory: "../data/features/sequential"