model_type: "sequential"
parameters: 
  model_generator: "sequential_three_conv_modules_generator"
  n_conv_filters: [32, 128, 256]
  filters_shape: [5, 5, 5]
  input_shape: [13, 216]
  adam_lr: 0.001
  batch_size: 32
  epochs: 1
  trained_models_dir: "../prod_models/candidate" # directory where the trained model should be stored after training
  trained_model_name: "seq_3conv_modules_be_nice"
  data_directory: "../data/features/sequential" # directory where the training, validation, and testing data
  train_data_directory: "../data/features/sequential"
  validation_data_directory: "../data/features/sequential"
  test_data_directory: "../data/features/sequential"
  
  