variables:
  GIT_DEPTH: 10

stages:
  - fetch
  - data
  - interface
  - thresholds
  - smoke
  
#Conformity Checks
#PEP8_Conformity:
# stage: PEP8
# image: geoazis/sentimentanalysis
# allow_failure: true
# script:
#   - "echo Running PEP8 Conformity checks to src folder"
#   - "cd src"
#   - "pytest --pep8 --disable-warnings"
# tags:
#   - jarvis

Fetch_data_and_models:
  stage: fetch
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script:
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "dvc remote modify --local nielspi password projectesa"
    - "dvc pull -f prod_models/candidate/ prod_data/test/"
  tags:
    - audio

Data_validation:
  stage: data
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script:
    - "echo Testing data schema and values"
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "pytest tests/test_cases/Data/"

  tags:
    - audio
    
Interface_validation: 
  stage: interface
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script:
    - "echo Testing DNNs interface specification"
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "pytest tests/test_cases/Model_test_cases/ --disable-warnings"
  tags:
    - audio
  allow_failure: true


Threshold_validation: 
  stage: thresholds
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script: 
    - "echo Testing DNN metrics against threshold values"
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "python tests/compute_models_performance.py"
    - "pytest tests/test_cases/Threshold_test_cases/ --disable-warnings"

  tags:
    - audio
    
Smoke_test:
  stage: smoke
  cache:
    key: default
    paths:
        - prod_data/test/
        - prod_models/candidate/
  script:
    - "echo Executing smoke test on the Raspberry Pi"
    - "source /home/pi/Documents/esa/venv/bin/activate"
    - "python src/stern_audio.py src/raspi_candidate_config.yml"
  tags:
    - audio
