model:
  dir: "siamese_tone_8_emotions/saved_models"
  file: "Emotion_Voice_Detection_Model.h5"
  type: "Siamese"
  n_mfcc: 50

test_data_dir: "./prod_data/test"
prod_models_dir: "./prod_models/deployed"

#audio recording properties
audio_channels: 1
audio_frequency: 44100
audio_length: 5 # length of audio in seconds

# interaction properties
iterations: 2 # for an infinite number of iterations, use -1
after_audio_analysis_pause: 1 # length of pause in seconds
before_recording_pause: 1

# logging
logging_directory: './logs'
logging_file_prefix: 'test_logging_file'
