model:
  dir: "seq_3conv_modules_vh5_retv2/saved_models"
  file: "Emotion_Voice_Detection_Model.h5"
  type: "Sequential"
  n_mfcc: 50

test_data_dir: "./prod_data/test"
prod_models_dir: "./prod_models/candidate"


#audio recording properties
audio_channels: 1
audio_frequency: 44100
audio_length: 5 # length of audio in seconds

#list of emotions being used in the prediction
#These codes should comply with the feature extraction part in training code
emotions:
  0: "neutral"
  1: "happy"
  2: "sad"
  3: "angry"
  4: "fearful"


# interaction properties
iterations: 2 # for an infinite number of iterations, use -1
after_audio_analysis_pause: 1 # length of pause in seconds
before_recording_pause: 1

# logging
logging_directory: '../logs'
logging_file_prefix: 'test_logging_file'